#!/bin/sh
# file: implement.sh

#-----------------------------------------------------------------------------
# Script to synthesize and implement the RTL provided for the clocking wizard
#-----------------------------------------------------------------------------

# Clean up the results directory
rm -rf results
mkdir results

# Copy unisim_comp.v file to results directory
cp $XILINX/verilog/src/iSE/unisim_comp.v ./results/

# Synthesize the Verilog Wrapper Files
echo 'Synthesizing System Monitor Wizard design with XST'
xst -ifn xst.scr
cp sysmon_wiz_v2_1_exdes.ngc results/

#  Copy the constraints files generated by Coregen
#echo 'Copying files from constraints directory to results directory'
#cp ../sysmon_wiz_v2_1.ucf results/

cd results

echo 'Running ngdbuild'
ngdbuild sysmon_wiz_v2_1_exdes

echo 'Running map'
map -timing sysmon_wiz_v2_1_exdes -o mapped.ncd

echo 'Running par'
par -w mapped.ncd routed mapped.pcf

echo 'Running trce'
trce -e 10 routed -o routed mapped.pcf

echo 'Running design through bitgen'
bitgen -w routed

echo 'Running netgen to create gate level model for the System Monitor Wizard example design'
netgen -ofmt vhdl -sim -tm sysmon_wiz_v2_1_exdes -w routed.ncd routed.vhd
cd ..
