rm -rf "../synth/__projnav" 
rm -rf "../synth/xst" 
rm -rf "../synth/_ngo" 

rm -rf tmp 
rm -rf _xmsgs 
rm -rf vio_sync_out32_xdb 
rm -rf vio_async_in96_xdb 
rm -rf vio_async_in100_xdb 
rm -rf vio_async_in192_xdb 
rm -rf icon4_xdb 

rm -rf xst 
rm -rf xlnx_auto_0_xdb 

rm -rf coregen.cgp
rm -rf coregen.cgc
rm -rf coregen.log 
rm -rf vio_sync_out32.asy 
rm -rf vio_sync_out32.cdc 
rm -rf vio_sync_out32.gise 
rm -rf vio_sync_out32.ise 
rm -rf vio_sync_out32.ncf 
rm -rf vio_sync_out32.ngc 
rm -rf vio_sync_out32.xco 
rm -rf vio_sync_out32.xise 
rm -rf vio_sync_out32_flist.txt 
rm -rf vio_sync_out32_readme.txt 
rm -rf vio_sync_out32_xmdf.tcl 

rm -rf vio_async_in100.asy 
rm -rf vio_async_in100.cdc 
rm -rf vio_async_in100.gise 
rm -rf vio_async_in100.ise 
rm -rf vio_async_in100.ncf 
rm -rf vio_async_in100.ngc 
rm -rf vio_async_in100.xco 
rm -rf vio_async_in100.xise 
rm -rf vio_async_in100_flist.txt 
rm -rf vio_async_in100_readme.txt 
rm -rf vio_async_in100_xmdf.tcl 


rm -rf vio_async_in192.asy 
rm -rf vio_async_in192.cdc 
rm -rf vio_async_in192.gise 
rm -rf vio_async_in192.ise 
rm -rf vio_async_in192.ncf 
rm -rf vio_async_in192.ngc 
rm -rf vio_async_in192.xco 
rm -rf vio_async_in192.xise 
rm -rf vio_async_in192_flist.txt 
rm -rf vio_async_in192_readme.txt 
rm -rf vio_async_in192_xmdf.tcl 

rm -rf vio_async_in96.asy 
rm -rf vio_async_in96.cdc 
rm -rf vio_async_in96.gise 
rm -rf vio_async_in96.ise 
rm -rf vio_async_in96.ncf 
rm -rf vio_async_in96.ngc 
rm -rf vio_async_in96.xco 
rm -rf vio_async_in96.xise 
rm -rf vio_async_in96_flist.txt 
rm -rf vio_async_in96_readme.txt 
rm -rf vio_async_in96_xmdf.tcl 

rm -rf icon4.gise 
rm -rf icon4.ise 
rm -rf icon4.ncf 
rm -rf icon4.ngc 
rm -rf icon4.xco 
rm -rf icon4.xise 
rm -rf icon4_flist.txt 
rm -rf icon4_readme.txt 
rm -rf icon4_xmdf.tcl 

rm -rf ise_flow_results.txt 
rm -rf xlnx_auto_0.ise 
rm -rf mig_top_vhdl.prj 
rm -rf mem_interface_top.syr 
rm -rf mig_top.ngc 
rm -rf mig_top.ngr 
rm -rf mig_top_xst.xrpt 
rm -rf mig_top.bld 
rm -rf mig_top.ngd 
rm -rf mig_top_ngdbuild.xrpt 
rm -rf mig_top_map.map 
rm -rf mig_top_map.mrp 
rm -rf mig_top_map.ngm 
rm -rf mig_top.pcf 
rm -rf mig_top_map.ncd 
rm -rf mig_top_map.xrpt 
rm -rf mig_top_summary.xml 
rm -rf mig_top_usage.xml 
rm -rf mig_top.ncd 
rm -rf mig_top.par 
rm -rf mig_top.xpi 
rm -rf smartpreview.twr 
rm -rf mig_top.ptwx 
rm -rf mig_top.pad 
rm -rf mig_top.unroutes 
rm -rf mig_top_pad.csv 
rm -rf mig_top_pad.txt 
rm -rf mig_top_par.xrpt 
rm -rf mig_top.twx 
rm -rf mig_top.bgn 
rm -rf mig_top.twr 
rm -rf mig_top.drc 
rm -rf mig_top_bitgen.xwbt
rm -rf mig_top.bit 

# Files and folders generated by create ise
rm -rf test_xdb
rm -rf _xmsgs
rm -rf test.gise
rm -rf test.xise
rm -rf test.xise

# Files and folders generated by ISE through GUI mode
rm -rf _ngo
rm -rf xst
rm -rf mig_top.lso 
rm -rf mig_top.prj 
rm -rf mig_top.xst 
rm -rf mig_top.stx 
rm -rf mig_top.syr 
rm -rf mig_top_prev_built.ngd 
rm -rf test.ntrc_log 
rm -rf mig_top_guide.ncd 
rm -rf mig_top.ut 
rm -rf mig_top.cmd_log 
rm -rf par_usage_statistics.html
rm -rf usage_statistics_webtalk.html
rm -rf webtalk.log
rm -rf device_usage_statistics.html 
rm -rf mig_top_summary.html 
